export const apimenu = {
    "HttpStatusResult": 200,
    "estado": true,
    "mensaje": null,
    "resultFisrt": {
        "codigoUsuario": "18522",
        "codigoEmpleado": "08522",
        "firmaUsuario": "U08522              ",
        "nombre": "KUFOY FONG HUMBERTO MARTIN              ",
        "correo": "Humberto.Kufoy@scotiabank.com.pe                            ",
        "cDR": "0000915",
        "codigoBT": "U08522",
        "CodigoRol": "3",
        "DescripcionRol": "Seguridad Informática",
        "CodigoCompania": "01",
        "CodigoCompaniaDelegado": "01"
    },
    "resultSecond": [
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCCTF     ",
            "DescripcionOpcion": "Certificación de Accesos                ",
            "Icono": "",
            "Menu": "",
            "Titulo": "Certificación de Accesos",
            "Programa": "../certificacion/certmenu.asp",
            "IXOpcion": "02.009",
            "IXOpcionPadre": "02",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCCTFMNU  ",
            "DescripcionOpcion": "Inicio                                  ",
            "Icono": "",
            "Menu": "",
            "Titulo": "Inicio",
            "Programa": "",
            "IXOpcion": "02.009.01",
            "IXOpcionPadre": "02.009",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCCTFBDJ01",
            "DescripcionOpcion": "Bandeja de Cert. de Accesos (Cert.)     ",
            "Icono": "",
            "Menu": "",
            "Titulo": "Bandeja de Cert. de Accesos (Cert.)",
            "Programa": "certbandeja.asp?vPerfil=C",
            "IXOpcion": "02.009.01.01",
            "IXOpcionPadre": "02.009.01",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCCTFBDJ02",
            "DescripcionOpcion": "Bandeja de Cert. de Accesos (Aud.)      ",
            "Icono": "",
            "Menu": "",
            "Titulo": "Bandeja de Cert. de Accesos (Aud.)",
            "Programa": "certbandeja.asp?vPerfil=A",
            "IXOpcion": "02.009.01.02",
            "IXOpcionPadre": "02.009.01",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCCTFBDJ03",
            "DescripcionOpcion": "Bandeja de Cert. de Accesos (Seg.Inf.)  ",
            "Icono": "",
            "Menu": "",
            "Titulo": "Bandeja de Certificación de Accesos (Seg.Inf.)",
            "Programa": "certbandeja.asp?vPerfil=SI",
            "IXOpcion": "02.009.01.03",
            "IXOpcionPadre": "02.009.01",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCCTFBDJ04",
            "DescripcionOpcion": "Bandeja de Cert. de Accesos (Ctrl.Op.)  ",
            "Icono": "",
            "Menu": "",
            "Titulo": "Bandeja de Cert. de Accesos (Ctrl.Op.)",
            "Programa": "certbandeja.asp?vPerfil=CO",
            "IXOpcion": "02.009.01.04",
            "IXOpcionPadre": "02.009.01",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCCTFBDJ05",
            "DescripcionOpcion": "Certificación Automática                ",
            "Icono": "",
            "Menu": "",
            "Titulo": "Certificación Automática",
            "Programa": "certbandejaautomatica.asp",
            "IXOpcion": "02.009.01.05",
            "IXOpcionPadre": "02.009.01",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCCTFBDJ06",
            "DescripcionOpcion": "Bandeja de Observaciones (Cert.)        ",
            "Icono": "",
            "Menu": "",
            "Titulo": "Bandeja de Observaciones (Cert.)",
            "Programa": "certbandejamensaje.asp?vPerfil=C",
            "IXOpcion": "02.009.01.06",
            "IXOpcionPadre": "02.009.01",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCCTFBDJ07",
            "DescripcionOpcion": "Bandeja de Observaciones (Aud.)         ",
            "Icono": "",
            "Menu": "",
            "Titulo": "Bandeja de Observaciones (Aud.)",
            "Programa": "certbandejamensaje.asp?vPerfil=A",
            "IXOpcion": "02.009.01.07",
            "IXOpcionPadre": "02.009.01",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCCTFBDJ08",
            "DescripcionOpcion": "Bandeja de Observaciones (Seg.Inf.)     ",
            "Icono": "",
            "Menu": "",
            "Titulo": "Bandeja de Observaciones (Seg.Inf.)",
            "Programa": "certbandejamensaje.asp?vPerfil=SI",
            "IXOpcion": "02.009.01.08",
            "IXOpcionPadre": "02.009.01",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCCTFBDJ09",
            "DescripcionOpcion": "Bandeja de Observaciones (Ctrl.Op.)     ",
            "Icono": "",
            "Menu": "",
            "Titulo": "Bandeja de Observaciones (Ctrl.Op.)",
            "Programa": "certbandejamensaje.asp?vPerfil=CO",
            "IXOpcion": "02.009.01.09",
            "IXOpcionPadre": "02.009.01",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCCTFBDJ10",
            "DescripcionOpcion": "Bandeja de Cert. de Accesos (Validador) ",
            "Icono": "",
            "Menu": "",
            "Titulo": "Bandeja de Cert. de Accesos (Validador)",
            "Programa": "certbandeja.asp?vPerfil=V",
            "IXOpcion": "02.009.01.10",
            "IXOpcionPadre": "02.009.01",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCCTFBDJ11",
            "DescripcionOpcion": "Bandeja de Observaciones (Validador)    ",
            "Icono": "",
            "Menu": "",
            "Titulo": "Bandeja de Observaciones (Validador)",
            "Programa": "certbandejamensaje.asp?vPerfil=V",
            "IXOpcion": "02.009.01.11",
            "IXOpcionPadre": "02.009.01",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCMNTMNU  ",
            "DescripcionOpcion": "Mantenimiento                           ",
            "Icono": "",
            "Menu": "",
            "Titulo": "Mantenimiento",
            "Programa": "",
            "IXOpcion": "02.009.02",
            "IXOpcionPadre": "02.009",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCMNTCIA  ",
            "DescripcionOpcion": "Compañías u Organizaciones              ",
            "Icono": "",
            "Menu": "",
            "Titulo": "Compañías u Organizaciones",
            "Programa": "mantenimientos/certmntcompania.asp",
            "IXOpcion": "02.009.02.01",
            "IXOpcionPadre": "02.009.02",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCMNTAPL  ",
            "DescripcionOpcion": "Aplicaciones                            ",
            "Icono": "",
            "Menu": "",
            "Titulo": "Aplicaciones",
            "Programa": "mantenimientos/certmntaplicativo.asp",
            "IXOpcion": "02.009.02.02",
            "IXOpcionPadre": "02.009.02",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCMNTPFN  ",
            "DescripcionOpcion": "Perfiles Funcionales                    ",
            "Icono": "",
            "Menu": "",
            "Titulo": "Perfiles Funcionales",
            "Programa": "mantenimientos/certmntperfilfuncional.asp",
            "IXOpcion": "02.009.02.03",
            "IXOpcionPadre": "02.009.02",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCMNTPFE  ",
            "DescripcionOpcion": "Perfil Funcional por Empleado           ",
            "Icono": "",
            "Menu": "",
            "Titulo": "Perfil Funcional por Empleado",
            "Programa": "mantenimientos/Masivo/PerfilPorEmpleado/LISTADO.asp",
            "IXOpcion": "02.009.02.04",
            "IXOpcionPadre": "02.009.02",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCMNTPPF  ",
            "DescripcionOpcion": "Perfiles de Aplicaciones por Perf.Func. ",
            "Icono": "",
            "Menu": "",
            "Titulo": "Perfiles de Aplicaciones por Perf.Func.",
            "Programa": "mantenimientos/certmntperfilfuncperfil.asp",
            "IXOpcion": "02.009.02.05",
            "IXOpcionPadre": "02.009.02",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCMNTPRA  ",
            "DescripcionOpcion": "Unidades Funcionales                    ",
            "Icono": "",
            "Menu": "",
            "Titulo": "Unidades Funcionales",
            "Programa": "mantenimientos/certmntprocesoaut.asp",
            "IXOpcion": "02.009.02.09",
            "IXOpcionPadre": "02.009.02",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCMNTGDL  ",
            "DescripcionOpcion": "Modificar Responsable de Certificación  ",
            "Icono": "",
            "Menu": "",
            "Titulo": "Modificar Responsable de Certificación",
            "Programa": "../Certificacion.net/GestionDelegado.aspx",
            "IXOpcion": "02.009.02.10",
            "IXOpcionPadre": "02.009.02",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCMNTPVE  ",
            "DescripcionOpcion": "Perfil Validador                        ",
            "Icono": "",
            "Menu": "",
            "Titulo": "Perfil Validador",
            "Programa": "mantenimientos/Masivo/AdminPerfilOperativo/LISTADO.ASP",
            "IXOpcion": "02.009.02.11",
            "IXOpcionPadre": "02.009.02",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCMTAMNU  ",
            "DescripcionOpcion": "Mantenimiento Avanzado                  ",
            "Icono": "",
            "Menu": "",
            "Titulo": "Mantenimiento Avanzado",
            "Programa": "",
            "IXOpcion": "02.009.03",
            "IXOpcionPadre": "02.009",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCMTACAL  ",
            "DescripcionOpcion": "Nuevos Periodos de Certificación        ",
            "Icono": "",
            "Menu": "",
            "Titulo": "Nuevos Periodos de Certificación",
            "Programa": "mantenimientos/certmntcalendario.asp",
            "IXOpcion": "02.009.03.01",
            "IXOpcionPadre": "02.009.03",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCMTAEQE  ",
            "DescripcionOpcion": "Equivalencia por Empleado               ",
            "Icono": "",
            "Menu": "",
            "Titulo": "Equivalencia por Empleado",
            "Programa": "Mantenimientos/Masivo/EquivalenciaPorEmpleado/LISTADO.asp",
            "IXOpcion": "02.009.03.02",
            "IXOpcionPadre": "02.009.03",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCMTAANM  ",
            "DescripcionOpcion": "Bandeja de Anomalías                    ",
            "Icono": "",
            "Menu": "",
            "Titulo": "Bandeja de Anomalías",
            "Programa": "mantenimientos/certmntanomalia.asp",
            "IXOpcion": "02.009.03.03",
            "IXOpcionPadre": "02.009.03",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCMTALPR  ",
            "DescripcionOpcion": "Log de Procesos                         ",
            "Icono": "",
            "Menu": "",
            "Titulo": "Log de Procesos",
            "Programa": "mantenimientos/Masivo/BandejaLogProceso/LISTADO.asp",
            "IXOpcion": "02.009.03.04",
            "IXOpcionPadre": "02.009.03",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCMTAMGP  ",
            "DescripcionOpcion": "Mantenimiento Guías de Proceso          ",
            "Icono": "",
            "Menu": "",
            "Titulo": "Mantenimiento Guías de Proceso",
            "Programa": "../Certificacion.net/GuiaProcesos.aspx",
            "IXOpcion": "02.009.03.05",
            "IXOpcionPadre": "02.009.03",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCMTADPR  ",
            "DescripcionOpcion": "Depuración de Periodos                  ",
            "Icono": "",
            "Menu": "",
            "Titulo": "Depuración de Periodos",
            "Programa": "../Certificacion.net/DepuracionProcesos.aspx",
            "IXOpcion": "02.009.03.06",
            "IXOpcionPadre": "02.009.03",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCMTAUPL  ",
            "DescripcionOpcion": "Carga de Archivos (V+ / IG)             ",
            "Icono": "",
            "Menu": "",
            "Titulo": "Carga de Archivos (V+ / IG)",
            "Programa": "../Certificacion.net/Upload.aspx",
            "IXOpcion": "02.009.03.07",
            "IXOpcionPadre": "02.009.03",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCMNTMAS  ",
            "DescripcionOpcion": "Mantenimientos Masivos                  ",
            "Icono": "",
            "Menu": "",
            "Titulo": "Mantenimientos Masivos",
            "Programa": "",
            "IXOpcion": "02.009.04",
            "IXOpcionPadre": "02.009",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCMNTMGC  ",
            "DescripcionOpcion": "Grupos de CDR                           ",
            "Icono": "I",
            "Menu": "",
            "Titulo": "Grupos de CDR",
            "Programa": "mantenimientos/Masivo/Grupos/LISTADO.asp",
            "IXOpcion": "02.009.04.01",
            "IXOpcionPadre": "02.009.04",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCMNTMPF  ",
            "DescripcionOpcion": "Perfiles Funcionales                    ",
            "Icono": "I",
            "Menu": "",
            "Titulo": "Perfiles Funcionales",
            "Programa": "mantenimientos/Masivo/PerfilesFuncionales/LISTADO.asp",
            "IXOpcion": "02.009.04.02",
            "IXOpcionPadre": "02.009.04",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCMNTMPFXE",
            "DescripcionOpcion": "Perfil Funcional por Empleado           ",
            "Icono": "I",
            "Menu": "",
            "Titulo": "Perfil Funcional por Empleado",
            "Programa": "mantenimientos/Masivo/PerfilFuncionalPorEmpleado/LISTADO.asp",
            "IXOpcion": "02.009.04.03",
            "IXOpcionPadre": "02.009.04",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCMNTMPAPF",
            "DescripcionOpcion": "Perfiles de Aplicaciones por Perf. Func.",
            "Icono": "I",
            "Menu": "",
            "Titulo": "Perfiles de Aplicaciones por Perf. Func.",
            "Programa": "mantenimientos/Masivo/PerfilesDeAplicacion/LISTADO.asp",
            "IXOpcion": "02.009.04.04",
            "IXOpcionPadre": "02.009.04",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCMNTMRC  ",
            "DescripcionOpcion": "Responsable de Certificación.           ",
            "Icono": "I",
            "Menu": "",
            "Titulo": "Responsable de Certificación.",
            "Programa": "mantenimientos/Masivo/DelegadosCDR/LISTADO.asp",
            "IXOpcion": "02.009.04.05",
            "IXOpcionPadre": "02.009.04",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCMNTDEP  ",
            "DescripcionOpcion": "Mantenimiento Depuración                ",
            "Icono": "I",
            "Menu": "",
            "Titulo": "Mantenimiento Depuración",
            "Programa": "",
            "IXOpcion": "02.009.05",
            "IXOpcionPadre": "02.009",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCMNTATB  ",
            "DescripcionOpcion": "Asignación de Tablas                    ",
            "Icono": "I",
            "Menu": "",
            "Titulo": "Asignación de Tablas",
            "Programa": "mantenimientos/Masivo/TablasConfig/CERTMNTASIGNARTABLA.ASP",
            "IXOpcion": "02.009.05.01",
            "IXOpcionPadre": "02.009.05",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCMNTCTB  ",
            "DescripcionOpcion": "Configuración de Tablas                 ",
            "Icono": "I",
            "Menu": "",
            "Titulo": "Configuración de Tablas",
            "Programa": "mantenimientos/Masivo/BandejaConfig/CERTLISTADOCONFIG.asp",
            "IXOpcion": "02.009.05.02",
            "IXOpcionPadre": "02.009.05",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCAYUMNU  ",
            "DescripcionOpcion": "Ayuda                                   ",
            "Icono": "",
            "Menu": "",
            "Titulo": "Ayuda",
            "Programa": "",
            "IXOpcion": "02.009.10",
            "IXOpcionPadre": "02.009",
            "InternalList": [],
            "MensajeError": ""
        },
        {
            "FirmaUsuario": "",
            "CodigoOpcion": "NCAYUAYU  ",
            "DescripcionOpcion": "Guia de ayuda                           ",
            "Icono": "I",
            "Menu": "",
            "Titulo": "Guia de ayuda",
            "Programa": "../Certificacion.net/Ayuda.aspx",
            "IXOpcion": "02.009.10.01",
            "IXOpcionPadre": "02.009.10",
            "InternalList": [],
            "MensajeError": ""
        }
    ]
}